apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - repositories.yaml
  - platform-vault.yaml
  - platform-minio.yaml
  - platform-observability.yaml
  - workloads-service-desk.yaml
  - workloads-webhook.yaml

