apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
type: Opaque
stringData:
  token: root-token
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: enterprise-vault
spec:
  provider:
    vault:
      server: http://host.docker.internal:18200
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: service-desk-secrets
  namespace: service-desk
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    name: enterprise-vault
    kind: ClusterSecretStore
  target:
    name: service-desk-secrets
    creationPolicy: Owner
  data:
    - secretKey: DJANGO_SECRET_KEY
      remoteRef:
        key: platform/service-desk
        property: DJANGO_SECRET_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webhook-ingestion-secrets
  namespace: webhook
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    name: enterprise-vault
    kind: ClusterSecretStore
  target:
    name: webhook-ingestion-secrets
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: platform/webhook
        property: API_KEY
    - secretKey: WEBHOOK_SECRET
      remoteRef:
        key: platform/webhook
        property: WEBHOOK_SECRET
