apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-desk-api.fullname" . }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /api/metrics/
    prometheus.io/port: "80"
spec:
  selector:
    app.kubernetes.io/name: {{ include "service-desk-api.fullname" . }}
  ports:
    - name: http
      port: 80
      targetPort: http
